#!/bin/bash
# Open the current repository in a browser

set -e
set -u
set -o pipefail

scripting_dir="$(dirname "$BASH_SOURCE")/scripting"
source "${scripting_dir}/color.sh"


usage() {
    echo "usage: webrepo"
}

show_help() {
    usage
    cat <<'EOF'

`webrepo` tries to find a URL for the current repository and open it in your browser.

If an HTTP or HTTPS URL is found, it is opened with the `open` command.
Otherwise, an SSH URL is assumed, and a naïve transformation is performed, so that
`ssh://git@github.com:barnardb/devaut.git` and `git@github.com:barnardb/devaut.git` become
`https://github.com/barnardb/devaut.git`
EOF
}


while (( $# > 0 )); do
    case "$1" in
        -'?' | --help) show_help; exit;;
        --) shift; break;;
        -*) usage_error "unknown option $1" "Use '--' to separate arguments from options";;
        *) break;;
    esac
    shift
done

[ $# -eq 0 ] || usage_error "unexpected arguments: $*"


local_branch="$(git name-rev --name-only HEAD)"
remote="$(git config "branch.${local_branch}.remote")"
remote_url="$(git config "remote.${remote}.url")"

process_url() {
    case "${1%:*}" in
        http | https) echo "$1";;
        ssh) process_url "${1#ssh://}";;
        *)  # assume SSH w/o "ssh://"
            host_and_path="${1#*@}"
            process_url "https://${host_and_path%:*}/${host_and_path##*:}"
            ;;
    esac
}

browser_url="$(process_url "${remote_url}")"
exec open "${browser_url}"
